#pragma once

// NOLINTBEGIN
#define ARCH_PAGE_SIZE_4K (0x1000)
#define ARCH_PAGE_SIZE_2M (512 * ARCH_PAGE_SIZE_4K)
#define ARCH_PAGE_SIZE_1G (512 * ARCH_PAGE_SIZE_2M)

#define ARCH_PAGE_SIZE_DEFAULT ARCH_PAGE_SIZE_4K
#define ARCH_MEM_PHYS_MAX 0x0000'000F'FFFF'FFFF'FFFF
// NOLINTEND
